# Generated by Django 6.0.3 on 2026-04-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pothole', 'Pothole'), ('water', 'Water Leak'), ('electricity', 'Electricity Fault'), ('waste', 'Waste Collection')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='report_photos/')),
                ('status', models.CharField(choices=[('received', 'Received - We have your report'), ('in_progress', 'In Progress - A team is working on it'), ('resolved', 'Resolved - Issue has been fixed')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
